# Generated by Django 2.2.18 on 2021-04-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_auto_20210418_1734'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basket',
            managers=[
            ],
        ),
    ]
