# Generated by Django 2.2.18 on 2021-04-18 10:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210418_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 10, 36, 6, 438858, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2021, 4, 18, 10, 36, 6, 438858, tzinfo=utc), verbose_name='дата рождения'),
        ),
    ]
