# Generated by Django 2.2.18 on 2021-04-16 14:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210416_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2021, 4, 16, 14, 46, 45, 498436, tzinfo=utc), verbose_name='дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 14, 46, 45, 498436, tzinfo=utc)),
        ),
    ]
