# Generated by Django 2.2.18 on 2021-04-19 10:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210418_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 10, 12, 27, 196507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2021, 4, 19, 10, 12, 27, 196507, tzinfo=utc), verbose_name='дата рождения'),
        ),
    ]
