# Generated by Django 2.2.18 on 2021-04-17 08:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20210416_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 8, 3, 56, 821299, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2021, 4, 17, 8, 3, 56, 821299, tzinfo=utc), verbose_name='дата рождения'),
        ),
    ]
